<?php
use AliyunMNS\Client;
use AliyunMNS\Requests\SendMessageRequest;
use AliyunMNS\Requests\CreateQueueRequest;
use AliyunMNS\Requests\BatchReceiveMessageRequest;
use AliyunMNS\Exception\MnsException;

class yzc{

	// 获取 阿里云 MNS 对象
	public function ali_mns_obj(){
		// 先往队列里面发消息试试
		$accessId = "LTAIZi0m78Ije8QG";
		$accessKey = "RGq2ALhgbSBfKmasIc5IDJJAlWu0Ya";
		$endPoint = "http://1691942791450205.mns.cn-shanghai.aliyuncs.com/";
		//这里需要先在控制台新建队列
		$queueName = 'aliyun-iot-a1rqyJeyTdP';
		//实例化获取MNS对象
		$client = new Client($endPoint, $accessId, $accessKey);
		$queue = $client->getQueueRef($queueName);
		return $queue;
	}

	public function msnew(){
		return new BatchReceiveMessageRequest(1,0);
	}

	private function fetch_redis(){
		$redis = new Redis();
		$redis->connect("127.0.0.1",6379);
		return $redis;
	}

	public function data_processing($data=''){
		$data = '{"payload":"eyJkZXZMaXN0IjpbeyJkZXZJZCI6MiwiZGV2Tm8iOiJoazAwMDEiLCJ2YXJMaXN0IjpbeyJ2YXJOYW1lIjoiTTM5NCIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjoxLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6Ik0zOTMiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MiwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJNMzk2IiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ1IiwidmFySWQiOjUsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTM5NyIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NSIsInZhcklkIjo2LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6Ik0zOTgiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDUiLCJ2YXJJZCI6NywiaXNXYXJuIjowfSx7InZhck5hbWUiOiJNNDAwIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ1IiwidmFySWQiOjgsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTQwMiIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NiIsInZhcklkIjo5LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6Ik00MDQiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDYiLCJ2YXJJZCI6MTAsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTQwNSAiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDYiLCJ2YXJJZCI6MTEsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTQwNyIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NiIsInZhcklkIjoxMiwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJNNDA4IiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ2IiwidmFySWQiOjEzLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6Ik00MDkiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDciLCJ2YXJJZCI6MTQsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTQxMCIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NyIsInZhcklkIjoxNSwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJNNDExIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ3IiwidmFySWQiOjE2LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6Ik00MTIiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDciLCJ2YXJJZCI6MTcsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTQxNCIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NyIsInZhcklkIjoxOCwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJNNDIzIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ4IiwidmFySWQiOjE5LCJpc1dhcm4iOjF9LHsidmFyTmFtZSI6Ik00MzYiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDgiLCJ2YXJJZCI6MjAsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiTTQ0MCIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0OCIsInZhcklkIjoyMSwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJNNDQxIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ4IiwidmFySWQiOjIyLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6Ik00NDIiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDgiLCJ2YXJJZCI6MjMsImlzV2FybiI6MX0seyJ2YXJOYW1lIjoiUlMwLjAiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MjQsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjEiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MjUsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjIiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MjYsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjMiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MjcsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjQiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MjgsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjUiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MjksImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjYiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzAsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMwLjciLCJ2YXJWYWx1ZSI6IjEiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzEsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjAiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzIsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjEiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzMsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjIiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzQsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjMiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzUsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjQiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzYsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjUiLCJ2YXJWYWx1ZSI6IjEiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzcsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjYiLCJ2YXJWYWx1ZSI6IjEiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzgsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxLjciLCJ2YXJWYWx1ZSI6IjEiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6MzksImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMyIiwidmFyVmFsdWUiOiI0NCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo0MCwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzMiLCJ2YXJWYWx1ZSI6IjQ0IiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjQxLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTNCIsInZhclZhbHVlIjoiNDQiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NDIsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlM1IiwidmFyVmFsdWUiOiI0NCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo0MywiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzYiLCJ2YXJWYWx1ZSI6IjI2OSIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo0NCwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzgiLCJ2YXJWYWx1ZSI6IjI3NyIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo0NSwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzEwIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjQ2LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTIiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NDcsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxNC4wIiwidmFyVmFsdWUiOiIxIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjQ5LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTQuMSIsInZhclZhbHVlIjoiMSIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo1MCwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzE0LjIiLCJ2YXJWYWx1ZSI6IjEiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NTEsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxNC4zIiwidmFyVmFsdWUiOiIxIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjUyLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTQuNCIsInZhclZhbHVlIjoiMSIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo1MywiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzAxNC41IiwidmFyVmFsdWUiOiIxIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjU0LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTQuNiIsInZhclZhbHVlIjoiMSIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo1NSwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzE1LjAiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NTYsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxNS4xIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjU3LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTUuMiIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo1OCwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzE1LjMiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NTksImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxNS40IiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjYwLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTUuNSIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo2MSwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzE1LjYiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NjIsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMxNiIsInZhclZhbHVlIjoiMSIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo2MywiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzE3IiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjY0LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMTgiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NjUsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMyMCIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo2NiwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzIyIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjY3LCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMjQiLCJ2YXJWYWx1ZSI6IjAyODAwNyIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo2OCwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzI4IiwidmFyVmFsdWUiOiIwMzAwMDAwMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo2OSwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzMyIiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjcwLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMzMiLCJ2YXJWYWx1ZSI6IjAiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzEsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMzNCIsInZhclZhbHVlIjoiMCIsInJlYWRUaW1lIjoiMjAxOC0xMi0yNiAxMjo1Nzo0NCIsInZhcklkIjo3MiwiaXNXYXJuIjowfSx7InZhck5hbWUiOiJSUzM1IiwidmFyVmFsdWUiOiIwIiwicmVhZFRpbWUiOiIyMDE4LTEyLTI2IDEyOjU3OjQ0IiwidmFySWQiOjczLCJpc1dhcm4iOjB9LHsidmFyTmFtZSI6IlJTMzYiLCJ2YXJWYWx1ZSI6IjIwMTgiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzQsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMzOCIsInZhclZhbHVlIjoiMTIiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzUsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlMzOSIsInZhclZhbHVlIjoiMjYiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzYsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlM0MCIsInZhclZhbHVlIjoiMTMiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzcsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlM0MSIsInZhclZhbHVlIjoiMTMiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzgsImlzV2FybiI6MH0seyJ2YXJOYW1lIjoiUlM0MiIsInZhclZhbHVlIjoiMzgiLCJyZWFkVGltZSI6IjIwMTgtMTItMjYgMTI6NTc6NDQiLCJ2YXJJZCI6NzksImlzV2FybiI6MH1dfV0sImNtZElkIjoxMDMsImd3U24iOiJXRzI4NUxMMDcxODA2MTgwMDE5OSIsImd3TmFtZSI6IldHMjgyV0xBTjE4MTAyODAwMTYxIn0=","messagetype":"upload","topic":"/a1rqyJeyTdP/WG282WLAN18102800161/up","messageid":1077790565426282496,"timestamp":1545800269}';
		$data_arr = json_decode($data,true);
		if($data_arr['messagetype'] == "upload"){
			$msg = json_decode(base64_decode($data_arr['payload']),true);
			$redis = $this->fetch_redis();
			$msg['timestamp'] = $data_arr['timestamp'];
			$redis->rpush("yzct",serialize($msg));
			// $count = $sth->rowCount();//受影响行数
		}
	}

	public function handle_msg_list(){
	    for ($i=0; $i < 100; $i++) {  // 10 * 16  每次运行处理160条
	    //先调用上面的方法，获取MNS对象
	      $queue = $this->ali_mns_obj();
	      //用MNS对象调用MNS提供的接口。这边是批量拉取活跃数据
	      //16代表每次最多拉取16条数据
	      //30代表失效，30秒拉取不到则失败
	      $obj_receives = $queue->batchReceiveMessage($this->msnew());
	      //拉取到数据之后，循环，使用getMessages()方法获取到消息内容
	      foreach ($obj_receives->getMessages() as $k) {
	        // 示例数据
	        // {"payload":"c3RfZm8=","messagetype":"upload","messageid":307,"topic":"/q5dL8yereAg/ssc-cl-00002/update","timestamp":1510991583}
	        //使用getMessageBody()方法获取消息的主体部分，注意，需要解密
	        $msg = $k->getMessageBody(); // payload部分数据，需 base64解码
	        $this->data_processing($msg);
	        // $obj = json_decode($msg);
	        // $d['str'] = base64_decode($obj->payload);
	        // $d['time'] = date('Y-m-d h:i:s', $obj->timestamp  );
	        // //这里是判断消息的类型。其实到这一步，已经成功获取到消息了
	        // if( $obj->messagetype == 'upload' ){
	        //   $this->ali_mns_handle($obj); // 如果是机器上传的信息，则处理
	        // }
	        // $str = json_encode($d);
	        // // 给硬件人员看
	        // if( $str!=false ){
	        //   Redis::lPush('ali_iot_mns_list', $str);
	        // }
	        // // 删除
	        $queue->deleteMessage(   $k->getReceiptHandle()  );
	      }
	    }
	    return MyResponse::success();
	  }
}

set_time_limit(0);
require_once('./mns-autoloader.php');
$yzc = new yzc();
// $result = $yzc->handle_msg_list();
$result = $yzc->data_processing();
print_r($result);
